services:

  postgresDB:
    image: postgres:17
    volumes:
      - restaurantVolume:/var/lib/postgresql/data
    ports:
      - 2345:5432
    env_file:
      - ./db.env
    networks:
      - restaurantNewtork
    container_name: postgresDB

  nestjs:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - postgresDB
    networks:
      - restaurantNewtork 
    env_file:
      - ./backend/.env
    restart: unless-stopped

networks:
  restaurantNewtork:
    driver: bridge

volumes:
  restaurantVolume: {}