@baseUrl = http://localhost:3000

###

POST {{baseUrl}}/item
Content-Type: application/json

{
    "name": "Carne de sol de boi",
    "description": "Carne de sol de boi daquele jeitão",
    "price": 45.50,
    "category": {
        "id": 1
    }
}

###

GET {{baseUrl}}/item/14

###

PUT {{baseUrl}}/item/16
Content-Type: application/json

{   
    "name": "Carne de porco",
    "description": "É carne e é de porco e agora é tira-gosto",
    "category": {
        "id": 4
    }
}

###

DELETE {{baseUrl}}/item/17


###