@baseUrl = http://localhost:3000

###

POST {{baseUrl}}/item-category
Content-Type: application/json

{
    "title": "Almoço"
}

###

GET {{baseUrl}}/item-category/1

###

DELETE {{baseUrl}}/item-category/6