@baseUrl = http://localhost:3000

### CREATE ITEM

POST {{baseUrl}}/item
Content-Type: application/json

{
    "name": "Carne de sol de porco",
    "description": "Almoço",
    "price": 61.00,
    "category": {
        "id": 1
    }
}

### GET ALL ITEMS

GET {{baseUrl}}/item

### GET SPECIFIC ITEM

GET {{baseUrl}}/item/14

### EDIT SPECIFIC ITEM

PUT {{baseUrl}}/item/16
Content-Type: application/json

{   
    "name": "Carne de boi",
    "description": "É carne e é boi e agora é tira-gosto",
    "category": {
        "id": 1
    }
}

### DELETE ITEM

DELETE {{baseUrl}}/item/19