@baseUrl = http://localhost:3000

###

POST {{baseUrl}}/item
Content-Type: application/json

{
    "name": "Carne de sol de boi",
    "description": "Carne de sol de boi daquele jeitão",
    "price": 45.50,
    "category": {
        "id": 1
    }
}

###