@baseUrl = http://localhost:3000

### POST ORDER

POST {{baseUrl}}/order
Content-Type: application/json

{

    "table": {
        "id": 1
    },
    "waiter": {
        "uuid": "dfd36b3b-f40b-42d9-ab51-aa1a8460cea9"
    },
    "orderItemList": [
        {
            "item": {
                "id": 1
            },
            "quantity": 3
        },
        {
            "item": {
                "id": 3
            },
            "quantity": 1
        }
        ]
}


### GET SPECIFIC ORDER

GET {{baseUrl}}/order/927ff0d9-3cd8-4b64-95cf-8d7b35736198
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMTRjMjJhM2QtYzQxNS00YmZlLTgwN2QtMGEzZmQzZGY0ZjEzIiwiZW1haWwiOiJhZG1pbkBlbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzk0MTczNjYsImV4cCI6MTczOTQyMDk2NiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.jLGAtHlSPYfHguCoqDceAOuuL-AHhQS6cW4QDphWdFU

### GET SPECIFIC ORDER'S ITEMS

GET {{baseUrl}}/order/order-items/31589a74-dcef-466d-b84b-b4fe7385a7b0

### GET ORDER BY TABLE'S ID

GET {{baseUrl}}/order?tableID=2

### FINISH ORDER 

PUT {{baseUrl}}/order/finish/2c622264-0dd9-4a09-8b4e-6c14b06c5b5d

### MANIPULATE ORDER ITEM

POST {{baseUrl}}/order/update_item/21d32ccf-d4b1-4a04-af02-44579c07af49
Content-Type: application/json

[
    {
        "item": {
            "id": 2
        },
        "quantity": 3
    },
    {
        "item": {
            "id": 1
        },
        "quantity": 4
    }
]

### DELETE ORDER

DELETE {{baseUrl}}/order/14182d19-1593-4107-888a-4b4038ef0891
