@baseUrl = http://localhost:3000

### POST ORDER

POST {{baseUrl}}/order
Content-Type: application/json

{

    "table": {
        "id": 1
    },
    "waiter": {
        "uuid": "f116cfba-be75-4d4c-a447-000eaf4506e2"
    },
    "orderItem": {
        "item": {
            "id": 1
        },
        "quantity": 2
    }

}

### GET SPECIFIC ORDER

GET {{baseUrl}}/order/7533a0c2-5e4e-4a21-bec4-87a98bd4c550


### GET SPECIFIC ORDER'S ITEM

GET {{baseUrl}}/order/order-items/d157d137-5477-4788-af2e-fc90928d6c3f

### FINISH ORDER 

PUT {{baseUrl}}/order/finish/87302fe0-6ee1-4fc8-b031-705f77de9804

### MANIPULATE ORDER ITEM

POST {{baseUrl}}/order/manipulate_order_item/31589a74-dcef-466d-b84b-b4fe7385a7b0
Content-Type: application/json

{
    "item": {
        "id": 2
    },
    "quantity": 0
}