@baseUrl = http://localhost:3000

POST {{baseUrl}}/order
Content-Type: application/json

{

    "table": {
        "id": 4
    },
    "waiter": {
        "uuid": "c58d3b3e-3ba0-495b-bb69-ae9b6a2db867"
    },
    "orderItem": {
        "item": {
            "id": 14
        },
        "quantity": 2
    }

}

###

GET {{baseUrl}}/order/7533a0c2-5e4e-4a21-bec4-87a98bd4c550


###