@baseUrl = http://localhost:3000

### CREATE NEW TABLE

POST {{baseUrl}}/table
Content-Type: application/json

{
    "name": "08"
}

### GET ONE TABLE

GET {{baseUrl}}/table/2

### GET ONE TABLE

GET {{baseUrl}}/table

### DELETE ONE TABLE

GET {{baseUrl}}/table/

### MISSING: DELETE TABLE/ UPDATE TABLE

