@baseUrl = http://localhost:3000

###

GET {{baseUrl}}/user

###

GET {{baseUrl}}/user/e7dbb9e8-0d8a-47dc-8efc-3366993f7bb9

###

POST {{baseUrl}}/user
Content-Type: application/json

{
    "email": "admin@email.com",
    "password": "adminadmin",
    "role": "admin"
}

###